[OPS-439] Improving the workflow when on d3 (#13)
Improving the workflow when on d3

Signed-off-by: Alex Lourie <alex.lourie@zepben.com>

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -23,11 +23,13 @@ inputs:
   NPM_TOKEN:
     description: "Token for authenticating with NPM_REPO."
     required: true
+  DOCS_TITLE:
+    description: "The title for docusaurus configuration"
+    required: true
 
 runs:
   using: "composite"
   steps: 
-
     - shell: sh
       if: ${{ inputs.TAG == 'yes' }}
       run: |
@@ -37,69 +39,122 @@ runs:
         git checkout release
 
     - shell: bash
+      env:
+        REPO_NAME: ${{ github.repository }}
+        DOCS_TITLE: ${{ inputs.DOCS_TITLE }}
       run: |
         # Copy all the templates if on Docusaurus3, but don't build
         cd docs
         /templates/build.sh --skip-build
         cd ..
 
-    - shell: sh
+    - name: Detect build folder and release-notes
+      shell: bash
+      run: |
+        docs="$(pwd)/docs"
+        site="$docs"
+        if [ -d ${docs}/site-config ]; then
+          site="${docs}/site-config"
+        fi
+        echo "docs=$docs" >> $GITHUB_ENV
+        echo "site=$site" >> $GITHUB_ENV
+
+        pushd "${site}"
+
+        if [ -f "release-notes.md" ]; then
+          echo "release_notes=$(pwd)/release-notes.md" >> $GITHUB_ENV
+        elif [ -f ${{ inputs.RELEASE_NOTES }} ]; then
+          echo "release_notes=${{ inputs.RELEASE_NOTES }}" >> $GITHUB_ENV
+        else
+          echo "I couldn't find release notes in ${{ inputs.RELEASE_NOTES }} nor in $(pwd)/release-notes.md"
+          exit 1
+        fi
+
+        popd
+
+
+    - name: Fetch dependencies
+      shell: bash
       run: |
         # "Update npmrc"
-        cd docs
+        pushd "${site}"
         rm -f .npmrc
         echo "@zepben:registry=${{inputs.NPM_REPO}}" >> .npmrc
         echo "//npm.pkg.github.com/:_authToken=${{inputs.NPM_TOKEN}}" >> .npmrc
-        # just in case, add EOL
-        echo "\n" >> .npmrc
 
         # fetch dependencies for all flows
         npm ci
-        cd ..
+        popd 
 
-    - shell: sh
+    - name: Create a version
+      shell: bash
       if: ${{ inputs.TAG == 'yes' }}
       run: |
-        # "VERSION TAG the new documentation"
-        cd docs
+        # "VERSION TAG the new documentation, do it in docs/ folder "
+        pushd "${docs}"
         npm run docusaurus docs:version ${{ inputs.VERSION }}
         cd ..
 
-    - shell: sh
+    - name: Update release notes
+      shell: bash
       if: ${{ inputs.TAG == 'yes' }}
       run: |
-        # "Update the release notes
+        # Update the release notes
         header="## [${{ inputs.VERSION }}]"
         changelog=$(sed -n -E "/${{ inputs.VERSION }}/,/## [[0-9]+\.[0-9]+\.[0-9]+]/ { /## \[/d;p }" ${{ inputs.CHANGELOG_FILE }})
         to_append="$header\n\n$changelog\n\n---\n"
-        cd docs
-        flat_version=$(echo ${{ inputs.VERSION }} | sed "s/\.//g")
-        sed -i "5i \|\[${{ inputs.VERSION }}\]\(\#${flat_version}\)\| \`$(date +'%d %B %Y')\` \|" ${{ inputs.RELEASE_NOTES }}
-        export ln=$(cat ${{ inputs.RELEASE_NOTES }} | grep -E -n "#+ \[[0-9]+.[0-9]+.[0-9]+" | head -1 | cut -d':' -f1)
-        if [ -z "$ln" ]; then
-          echo "${changelog}\n\n---\n" >> ${{ inputs.RELEASE_NOTES }}
-        else
-          awk -v n=$ln -v s="$to_append" 'NR == n {print s} {print}' ${{ inputs.RELEASE_NOTES }} > release-notes.tmp
-          mv release-notes.tmp ${{ inputs.RELEASE_NOTES }}
-        fi
-        cd ..
 
-    - shell: sh
+        pushd "${site}"
+
+        flat_version=$(echo ${{ inputs.VERSION }} | sed "s/\.//g")
+        sed -i "5i \|\[${{ inputs.VERSION }}\]\(\#${flat_version}\)\| \`$(date +'%d %B %Y')\` \|" "${release_notes}"
+        export ln=$(cat "${release_notes}" | grep -E -n "#+ \[[0-9]+.[0-9]+.[0-9]+" | head -1 | cut -d':' -f1)
+        if [ -z "$ln" ]; then
+          echo "${changelog}\n\n---\n" >> "${release_notes}"
+        else
+          awk -v n=$ln -v s="$to_append" 'NR == n {print s} {print}' "${release_notes}" > release-notes.tmp
+          mv release-notes.tmp ${release_notes}
+        fi
+        popd
+
+    - name: Build the docs
+      shell: bash
       run: |
         # "Build the documentation site"
-        cd docs
+        pushd "${site}"
         npm run build
-        cd ..
 
-    - shell: sh
+        # Finally, we can copy out the build directory from site-config if in docusaurus3, so that zipper can do its thing
+        if [ $(basename $(pwd)) == "site-config" ]; then
+          mv build ..
+        fi
+
+        popd
+
+    - name: Commit the results
+      shell: bash
       if: ${{ inputs.TAG == 'yes' }}
       run: |
         # "Commit the release branch"
         cd docs
-        git restore .npmrc
+
+        if [ -d site-config ]; then
+          # if on Docusaurus3, copy over the artefacts
+          \cp -frL site-config/versioned_docs/* archive/versioned_docs/
+          \cp -frL site-config/versioned_sidebars/* archive/versioned_sidebars/
+          \cp -rf site-config/versions.json archive/
+
+          # restore .npmrc
+          git restore site-config/.npmrc
+        else
+          git restore .npmrc
+        fi
+
         git add .
         git config user.email "ci.github@zepben.com"
         git config user.name "Github CI"
         git commit -m "Committing doc changes to docusaurus. [skip ci]"
         git push origin release
-        cd ..
+
+        # Get back home
+        cd
